version: "3.9"
services:
    db:
        image: mysql:5.7
        restart: always
        volumes:
            - data_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: wordpress
    wordpress:
        depends_on:
            - db
        image: wordpress:5.8
        restart: always
        expose:
            - "80"
        volumes:
            - data_wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
    nginx:
        image: nginx:1.21
        depends_on:
            - wordpress
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 3000:3000

volumes:
    data_db: {}
    data_wordpress: {}
